### PR TITLE
Allow travis

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
OK, so it seems this would work, but only if we allow PRs only from branches within the repo (i.e., from current collaborators) rather than the usual fork model for anyone. I wonder if this is viable or not.

**Comment by martindurant** [comment]
Of course, we could defer tests to authors on their own credentials, and then let travis only run tests on the master branch after merge

**Comment by martindurant** [comment]
@TomAugspurger , to fill you in: this is an attempt to tests the code against real gdrive using real creds, to avoid messing around with vcrpy.

**Comment by TomAugspurger** [comment]
Does allowing PRs from branches risk exposing credentials?

**Comment by martindurant** [comment]
It could, so travis forbids it

**Comment by TomAugspurger** [comment]
I suppose mocking would be quite difficult? I see https://github.com/googleapis/google-api-python-client/blob/master/tests/test_mocks.py, which provides some basics...

**Comment by martindurant** [comment]
Would involve re-writing the google api in the mock class. Can check for consistency with past code, but not really correct working

**Comment by TomAugspurger** [comment]
OK. I feel a bit uneasy about adding real user credentials to public CI,
but I don't have a strong prior here on what's best.

**Comment by martindurant** [comment]
The travis system is certain meant for this situation, but it has its own pain. I don't want to invoke vcrpy again... So I don't have a good solution either (except: don't use CI!!)

**Comment by TomAugspurger** [comment]
Given that I'm currently fighting it, I'm +1 to avoiding vcrpy :)

**Pull request closed without merging**
